name: backstreets
description: A game server of some kind.
version: 0.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.8.1'

dependencies:
  path:
  meta:

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
